export const CURRICULUM = [
    {
        week: '1',
        title: '토큰화(Tokenization)',
        emoji: '🧩',
        subtitle: 'AI가 글자를 읽는 법',
        description: '텍스트를 숫자로 변환하는 토큰화(Tokenization)의 원리를 배우고, BPE 알고리즘을 체험합니다.',
        introPath: '/week1/intro',
        labPath: '/week1',
        color: '#fbbf24',
        status: 'ready',
        tags: ['토큰', 'BPE', '인코딩'],
    },
    {
        week: '2',
        title: '확률과 언어 모델',
        emoji: '🎲',
        subtitle: '다음 단어 예측하기',
        description: 'AI가 다음에 올 단어를 예측하는 확률적 원리와 Temperature 파라미터의 역할을 배웁니다.',
        introPath: '/week2/intro',
        labPath: '/week2',
        color: '#34d399',
        status: 'ready',
        tags: ['확률', 'Softmax', 'Temperature'],
    },
    {
        week: '3',
        title: '원-핫 인코딩',
        emoji: '1️⃣',
        subtitle: '단어를 숫자로 바꾸는 첫 번째 방법',
        description: '원-핫 인코딩의 원리를 체험하고, 왜 이 방식만으로는 부족한지 직접 확인합니다.',
        introPath: '/week3/intro',
        labPath: '/week3',
        color: '#f59e0b',
        status: 'ready',
        tags: ['원-핫', '인코딩', '희소벡터'],
    },
    {
        week: '4',
        title: '임베딩 은하수',
        emoji: '🌌',
        subtitle: '3D 우주 속 단어 별 만들기',
        description: '임베딩 벡터가 어떻게 단어의 의미를 담는지 3D 은하수에서 체험합니다.',
        introPath: '/week4/intro',
        labPath: '/week4',
        color: '#7c5cfc',
        status: 'ready',
        tags: ['임베딩', '벡터', '유사도'],
    },
    {
        week: '5',
        title: '경사하강법 레이싱',
        emoji: '🏎️',
        subtitle: '학습률 & 모멘텀으로 최저점 레이싱!',
        description: '경사하강법의 원리를 배우고, 학습률과 모멘텀을 직접 설정해 3D 손실 지형에서 레이싱합니다.',
        introPath: '/week5/intro',
        labPath: '/week5',
        color: '#f43f5e',
        status: 'ready',
        tags: ['경사하강법', '학습률', '모멘텀'],
    },
    {
        week: '6',
        title: '신경망의 기초',
        emoji: '🕸️',
        subtitle: '뉴런과 시냅스를 코드로!',
        description: '인공 뉴런(Perceptron)의 구조를 이해하고, 다층 퍼셉트론(MLP)을 만들어봅니다.',
        introPath: '/week6/intro',
        labPath: '/week6',
        color: '#60a5fa',
        status: 'ready', // To be implemented
        tags: ['퍼셉트론', 'MLP', '활성화함수'],
    },
    {
        week: '7',
        title: '역전파 탐험',
        emoji: '🔄',
        subtitle: '오류를 거슬러 올라가기',
        description: '신경망이 오차를 통해 스스로 학습하는 역전파 과정을 단계별로 체험합니다.',
        introPath: '/week7/intro',
        labPath: '/week7',
        color: '#10b981',
        status: 'ready',
        tags: ['역전파', '가중치', '오차'],
    },
    {
        week: '8',
        title: '시퀀스와 포지션 (RNN)',
        emoji: '〰️',
        subtitle: '순서를 기억하는 방법',
        description: '문맥을 이해하기 위한 과거의 시도(RNN)와 트랜스포머가 위치 정보를 처리하는 방법(Positional Encoding)을 배웁니다.',
        introPath: '/week8/intro',
        labPath: '/week8',
        color: '#a78bfa',
        status: 'ready',
        tags: ['RNN', 'LSTM', '포지션인코딩'],
    },
    {
        week: '10-11',
        title: '어텐션 게임',
        emoji: '✨',
        subtitle: 'Query · Key · Value로 집중하기!',
        description: 'Transformer의 핵심인 어텐션 메커니즘을 직접 조작하며 이해합니다.',
        introPath: '/week10/intro',
        labPath: '/week10',
        color: '#3b82f6',
        status: 'ready',
        tags: ['어텐션', 'Q/K/V', '소프트맥스'],
    },
    {
        week: '12',
        title: 'RMS 정규화',
        emoji: '⚡',
        subtitle: '폭발하는 숫자를 제어하라!',
        description: '정규화가 왜 필요한지, RMSNorm이 어떻게 값을 안정시키는지 체험합니다.',
        introPath: '/week12/intro',
        labPath: '/week12',
        color: '#f59e0b',
        status: 'ready',
        tags: ['정규화', 'RMSNorm', '안정성'],
    },
    {
        week: '13',
        title: 'GPT 아키텍처',
        emoji: '🏗️',
        subtitle: '생성형 AI의 설계도',
        description: 'Decoder-only 구조인 GPT의 전체 아키텍처를 하나씩 조립하며 이해합니다.',
        introPath: '/week13/intro',
        labPath: '/week13',
        color: '#ef4444',
        status: 'ready', // To be implemented
        tags: ['GPT', 'Decoder', '생성형AI'],
    },
    {
        week: '14',
        title: 'AI 조련하기 (SFT & RLHF)',
        emoji: '🐕',
        subtitle: '똑똑한 비서 만들기',
        description: 'GPT가 인간의 의도에 맞게 대답하도록 가르치는 SFT와 RLHF(강화학습) 과정을 배웁니다.',
        introPath: '/week14/intro',
        labPath: '/week14',
        color: '#8b5cf6',
        status: 'ready',
        tags: ['SFT', 'RLHF', 'PPO'],
    },
    {
        week: '15-17',
        title: '바이브 코딩 해커톤',
        emoji: '💻',
        subtitle: 'AI와 함께 코딩하기!',
        description: 'AI 코딩 어시스턴트와 함께 나만의 프로젝트를 만드는 해커톤!',
        introPath: '/week15/intro',
        labPath: '/week15',
        color: '#ec4899',
        status: 'ready',
        tags: ['바이브코딩', '해커톤', '프로젝트'],
    },
    {
        week: '심화',
        title: 'MicroGPT 해부학',
        emoji: '🧬',
        subtitle: 'GPT의 실제 코드 뜯어보기',
        description: 'Transformer의 내부 구조와 핵심 코드를 단계별로 분석하며 원리를 마스터합니다.',
        introPath: '/advanced-gpt/intro',
        labPath: '/advanced-gpt/intro',
        color: '#ec4899',
        status: 'ready',
        tags: ['Transformer', 'PyTorch', '아키텍처'],
    },
];
